//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidacionesUDEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class validaciones1
    {
        public string usuario { get; set; }
        public string password { get; set; }
        public string password2 { get; set; }
        public string email { get; set; }
        public string email2 { get; set; }
        public int edad { get; set; }
        public int edad2 { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fecha2 { get; set; }
        public string textoPequenio { get; set; }
        public string textMediano { get; set; }
        public string textoGrande { get; set; }
        public string tarjetaDeCredito { get; set; }
    }
}
